# Generated by Django 5.2.1 on 2025-06-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('users', '0003_user_address_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('app', 'In-app Messaging')], default='phone', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
