# Generated by Django 5.2.1 on 2025-06-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_delete_customerprofile'),
        ('mechanics', '0003_specialty_mechanic_delete_mechanicprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('appliance', 'Appliance Repair'), ('hvac', 'HVAC'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField()),
                ('address', models.TextField()),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in hours')),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanics.mechanic')),
            ],
        ),
    ]
